# Generated by Django 4.2.1 on 2023-06-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150)),
                ('url', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('dataInicio', models.DateField(default=None, null=True)),
                ('dataFim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimenteVoce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoriosRealizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=10)),
                ('semestre', models.CharField(max_length=4)),
                ('disciplina', models.CharField(max_length=50)),
                ('ects', models.CharField(max_length=2)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OutrasCompetencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('dataInicio', models.DateField(default=None, null=True)),
                ('dataFim', models.DateField(blank=True, default=None, null=True)),
                ('instituicao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PercursoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('dataInicio', models.DateField(default=None, null=True)),
                ('dataFim', models.DateField(blank=True, default=None, null=True)),
                ('instituicao', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectosDesenvolvidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=3000)),
                ('imagem', models.FileField(blank=True, null=True, upload_to='imagens/')),
            ],
        ),
    ]
