# Generated by Django 4.2.1 on 2023-06-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienciaprofissional',
            name='dataFim',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='experienciaprofissional',
            name='dataInicio',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='outrascompetencias',
            name='dataFim',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='outrascompetencias',
            name='dataInicio',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='percursoacademico',
            name='dataFim',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='percursoacademico',
            name='dataInicio',
            field=models.DateField(default=None, null=True),
        ),
    ]
