# Generated by Django 4.2.1 on 2023-06-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_experienciaprofissional_datafim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectosdesenvolvidos',
            name='descricao',
            field=models.CharField(max_length=3000),
        ),
    ]
