# Generated by Django 4.2.1 on 2023-06-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_projectosdesenvolvidos_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienciaprofissional',
            name='descricao',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='laboratoriosrealizados',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='ano',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='semestre',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='outrascompetencias',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='percursoacademico',
            name='instituicao',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='percursoacademico',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='projectosdesenvolvidos',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
