# Generated by Django 4.2.1 on 2023-06-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_experienciaprofissional_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimenteVoce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
    ]
