# Generated by Django 4.2.1 on 2023-06-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_experimentevoce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='url',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='experienciaprofissional',
            name='descricao',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='projectosdesenvolvidos',
            name='descricao',
            field=models.TextField(max_length=3000),
        ),
    ]
