# Generated by Django 4.2.1 on 2023-06-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_contacto_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienciaprofissional',
            name='dataFim',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='outrascompetencias',
            name='dataFim',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='percursoacademico',
            name='dataFim',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
