# Generated by Django 4.2.1 on 2023-06-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_experienciaprofissional_datafim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienciaprofissional',
            name='dataFim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
