# Generated by Django 4.2.1 on 2023-06-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_experienciaprofissional_datafim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciatura',
            name='semestre',
            field=models.CharField(max_length=6),
        ),
    ]
