# Generated by Django 4.2.1 on 2023-06-10 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_licenciatura_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenciatura',
            name='nome',
        ),
    ]
