# Generated by Django 4.2.1 on 2023-06-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_licenciatura_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciatura',
            name='ano',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='semestre',
            field=models.CharField(max_length=4),
        ),
    ]
